hu.kramo.GameShelf.json, src/utils/heroic_parser.py
Thanks to Mirko, GitHub showed me this project.
Man, this is good.
I changed the way it imports images from Heroic (using it's internal cache instead of temporal path used for Steam and shortcuts)
I also noticed that you hard coded the path to source in flatpak manifest, so I fixed that too.
Looking forward to see what this becomes
=> Improve images import from Heroic

po/POTFILES, po/cartridges.pot, po/hu.po, po/ta.po, src/utils/bottles_parser.py, src/utils/heroic_parser.py, src/utils/steam_parser.py
- Fixed typos in strings.
- Added source locations to POTFILES.
- Updated Tamil translation in `ta.po`.
- Regenerated the POT template and PO files automatically using the following commands:-
- `meson /tmp/translation-build`
- `meson compile -C /tmp/translation-build cartridges-pot`
- `meson compile -C /tmp/translation-build cartridges-update-po`
=> Update POTFILES, fix strings, regenerate PO and POT file, Update ta.po

src/game.py
The function was getting a bit convoluted to follow, and there was a maintenance burden of having to remember that "shell=True" should only be true if the argument is a single string to be passed exactly as-is to the shell. If it's a list, only the first value in the list would be ran as the shell command and the rest would be given as arguments to the shell itself.
Therefore, it's been refactored to automatically determine shell-mode based on whether "args" is a list or a string.
On Windows, we now generate a correctly escaped shell-string via "shlex". This ensures that we properly support spaces inside quoted launch arguments, by auto-escaping them on a per-argument basis.
The extra pylint hint is needed because the import is detected as unused on non-Windows machines.
=> Refactor game launching, and fix Windows support

data/gtk/preferences.blp
This way switches are activated when the row is clicked.
=> preferences: Use activatable-widget for action rows with switches

src/main.py
Sorting the list alphabetically since it was really arbitrarily arranged.
Updated with my new GitHub account name.
=> Sort contributors alphabetically

src/game.py, src/importers/bottles_importer.py, src/importers/heroic_importer.py, src/importers/itch_importer.py, src/importers/lutris_importer.py, src/importers/steam_importer.py, src/main.py, src/meson.build, src/preferences.py, src/shared.py, src/utils/save_cover.py, src/utils/steamgriddb.py
Moved the `Gio.Settings` schemas to `shared.py` module to decouple a little bit more from the window object
=> Moved schemas to shared module

flatpak/hu.kramo.Cartridges.Devel.json, src/keyboard_emulator.py, src/main.py, src/meson.build
Base work on controller support, done in tandem between Kramo and I.
=> initial work on controller support

src/importer/importer.py
- Progress is 0 by default
- 10% for the sources progress
- 90% for the pipelines progress
=> Fixed importer progressbar stuck at 100%

data/gtk/preferences.blp, src/details_window.py, src/game.py, src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/lutris_source.py, src/importer/sources/steam_source.py, src/main.py, src/preferences.py, src/store/managers/display_manager.py, src/window.py
- Removed win.games
- Removed allow_side_effects in `game.__init__`
- Fix wrong flatpak location name for the file picker button
=> Various cleanups

src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/lutris_source.py, src/importer/sources/steam_source.py, src/shared.py.in
- using pathlib syntax for locations
- added `home` and `flatpak_dir` to shared
- simplifed `Source.available_on`
=> Sources paths fix

src/details_window.py, src/main.py, src/preferences.py, src/store/store.py, src/window.py
- Store games by source
- Added convenience dunder methods (contains, iter, len, getitem)
- Added store.get
- Changed `enable_in_pipeline` for `toggle_in_pipeline`
=> Store improvements

data/gtk/preferences.blp, data/hu.kramo.Cartridges.gschema.xml.in, flatpak/hu.kramo.Cartridges.Devel.json, src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/lutris_source.py, src/importer/sources/source.py, src/importer/sources/steam_source.py, src/logging/setup.py, src/preferences.py, src/store/managers/local_cover_manager.py
Various Heroic improvement, mainly a refactor to address #148
This PR is not ready for merge, I still need to test it. 
Feel free to test the code independently, testers are always appreciated.
Changes:
- Reading the sub-sources' `installed.json` for installation status instead of the store cache
- Support for Amazon Prime Gaming through Nile in Heroic
- Support importing the Heroic hidden status for games  
Small fixes along the way:
- Added more debug info to the steam source
- Dropped PIL's logger to `WARNING`
=> Heroic fixes and improvements

src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/location.py, src/importer/sources/lutris_source.py, src/importer/sources/source.py, src/importer/sources/steam_source.py, src/preferences.py
Various improvements to the source location
Changes:
- Using named tuples for source locations
- Clarified location sub-paths
- Moved invalid picked location message to the location class
=> Locations improvements

src/importer/importer.py, src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/lutris_source.py, src/importer/sources/source.py, src/importer/sources/steam_source.py, src/preferences.py
- Additional fix, lutris source db subpath
=> Fix source id being translated

src/importer/sources/heroic_source.py
That way we can ensure that correct game is ran, although it's rare, there is a possibility for appNames to be the same across integrations
=> Specify runner in heroic protocol

src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/location.py, src/importer/sources/lutris_source.py, src/importer/sources/retroarch_source.py, src/importer/sources/source.py, src/importer/sources/steam_source.py, src/preferences.py
- Simplified some preferences code
- Added type hints to locations
- Made locations not shared between source instances (source of a bug)
- Updated source iter to resolve locations correctly
=> Various fixes for locations

src/utils/rate_limiter.py, src/utils/steam.py
Various typing improvements following Kramo's work.
- Improved the rate limtier code to be cleaner and ditch `None`
- Explicitly using keywords to build `SteamManifestData` typed dicts
=> Typing improvements

src/importer/sources/bottles_source.py, src/importer/sources/flatpak_source.py, src/importer/sources/heroic_source.py, src/importer/sources/itch_source.py, src/importer/sources/legendary_source.py, src/importer/sources/lutris_source.py, src/importer/sources/source.py, src/importer/sources/steam_source.py, src/logging/session_file_handler.py
- Using `make_executable` correctly in the places where it's supposed to
- Handling UTF-8 decode errors when reading a log file to compress it (deletes corrupted file)
=> Improvements to game executable + better handling of corrupted log files

po/POTFILES
details-window.blp > details-dialog.blp
details_window.py > details_dialog.py
=> potfiles: Add renamed files

po/LINGUAS, po/te.po
Did it manually as it is easier for me,
=> feat(l10n): Added Telugu (te) Language Support for Cartridges

cartridges/importer/importer.py, cartridges/main.py, cartridges/preferences.py, data/gtk/preferences.blp, data/page.kramo.Cartridges.gschema.xml.in
=> Add an option to import games automatically
